apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zirong-app
spec:
  project: default
  source:
    repoURL: "https://github.com/NgZiRong1984/zirong-k8s-manifest.git"
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: zirong-ns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
