apiVersion: apps/v1
kind: Deployment
metadata:
  name: zirong-app
  namespace: zirong-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zirong-app
  template:
    metadata:
      labels:
        app: zirong-app
    spec:
      containers:
        - name: zirong-app
          image: zirong-app-image:latest
          ports:
            - containerPort: 80
