apiVersion: apps/v1
kind: Deployment
metadata:
  name: zirong-app
  namespace: zirong-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zirong-app
  template:
    metadata:
      labels:
        app: zirong-app
    spec:
      containers:
        - name: zirong-app
          image: nginx:latest
          ports:
            - containerPort: 80
