apiVersion: v1
kind: Service
metadata:
  name: zirong-app-service
  namespace: zirong-ns
spec:
  selector:
    app: zirong-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
